tasks:
- init: |
    echo "dotnet"
    wget "https://dot.net/v1/dotnet-install.sh"
    chmod +x dotnet-install.sh
    ./dotnet-install.sh --install-dir /workspace/dotnet
    rm dotnet-install.sh
    sudo ln -s /workspace/dotnet/dotnet /usr/bin/dotnet
  command: |
        if [ -z ${ADYEN_HMAC_KEY+x} ] || [[ -z ${ADYEN_API_KEY+x} ]] || [[ -z ${ADYEN_CLIENT_KEY+x} ]] || [[ -z ${ADYEN_MERCHANT_ACCOUNT+x} ]]; then
            echo "Expected environment variables not found. Please set the ADYEN_HMAC_KEY, ADYEN_API_KEY, ADYEN_CLIENT_KEY, ADYEN_MERCHANT_ACCOUNT environment variables and rerun session https://gitpod.io/variables."

# exposed ports
ports:
- port: 8080
  onOpen: open-preview
  visibility: public

vscode:
  extensions:
    - ms-dotnettools.csharp
