name: .NET

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/readme.md'
      - readme.md
      - .gitignore
      - .gitpod.yml
      - LICENSE
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/readme.md'
      - readme.md
      - .gitignore
      - .gitpod.yml
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
